fitnessclub/src/Entity/GroupTraining.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GroupTrainingRepository")
 */
class GroupTraining
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Required")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank(message="Required")
     * @ORM\Column(type="string", length=255)
     */
    private $master_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_expired;

    public function __construct()
    {
        $this->userTraining = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMasterName(): ?string
    {
        return $this->master_name;
    }

    public function setMasterName(string $master_name): self
    {
        $this->master_name = $master_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsExpired(): ?bool
    {
        return $this->is_expired;
    }

    public function setIsExpired(bool $is_expired): self
    {
        $this->is_expired = $is_expired;

        return $this;
    }
}

fitnessclub/src/Entity/UserTraining.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserTrainingRepository")
 */
class UserTraining
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="userTrainings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GroupTraining")
     * @ORM\JoinColumn(nullable=false)
     */
    private $groupTraining;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NotificationType")
     * @ORM\JoinColumn(nullable=false,name="notification_type_id", referencedColumnName="id")
     */
    private $notification_type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_deleted;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * Set user
     *
     * @param User
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGroupTraining(): ?GroupTraining
    {
        return $this->groupTraining;
    }

    public function setGroupTraining(?GroupTraining $groupTraining): self
    {
        $this->groupTraining = $groupTraining;

        return $this;
    }

    public function getNotificationType(): ?NotificationType
    {
        return $this->notification_type;
    }

    public function setNotificationType(?NotificationType $notification_type): self
    {
        $this->notification_type = $notification_type;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->is_deleted;
    }

    public function setIsDeleted(bool $is_deleted): self
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

}

fitnessclub/src/Controller/UserTrainingController.php
<?php

namespace App\Controller;

use App\Entity\GroupTraining;
use App\Entity\NotificationType;
use App\Entity\User;
use App\Entity\UserTraining;
use Symfony\Component\HttpFoundation\Request;
use Exception;
use ReflectionClass;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class UserTrainingController extends AbstractController
{
    /**
     * @Route("/profile/subscribe/{id}")
     */

    public function subscribe($id = null, Request $request){
        try {
            new ReflectionClass('ReflectionClass' . ((int)$id . "" !== $id));
        } catch (Exception $e) {
            throw new NotFoundHttpException("Wrong input data");
        }

        $training = $this->getDoctrine()->getRepository(GroupTraining::class)->find((int)$id);

        var_dump(sizeof($this->getUser()->getUserTrainings()));

        foreach ($this->getUser()->getUserTrainings() as $userTraining){
            if($training === $userTraining->getGroupTraining()){
                return $this->redirectToRoute('viewUserGroupTraining',['id'=>$userTraining->getId()]);
            }
        }

        if($training && $training->getIsExpired() == false){
            $notification_types_repository    = $this->getDoctrine()->getRepository(NotificationType::class);
            $user_training = new UserTraining();
            $user_training->setUser($this->getUser());
            $user_training->setGroupTraining($training);

            $form = $this->getSubscribeForm($user_training);
            $form->add('subscribe', SubmitType::class, ['label' => 'Subscribe', 'attr'=>['class' => 'btn btn-info btn-md', 'style' => 'float:right']]);

            $form->handleRequest($request);
            if ($request->isMethod('POST')) {
                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $user_training->setIsDeleted(false);
                    $entityManager->persist($user_training);
                    $entityManager->flush();

                    return $this->redirectToRoute('profile');
                }
            }



            return $this->render('user_training/subscribe.html.twig', [
                'form' => $form->createView(),
                'user' => $this->getUser(),
                'training'=>$training
            ]);


        }
        throw new NotFoundHttpException("Something went wrong");
    }

    public function view($id){
        try {
            new ReflectionClass('ReflectionClass' . ((int)$id . "" !== $id));
        } catch (Exception $e) {
            throw new NotFoundHttpException("Wrong input data");
        }

        $user_training = $this->getDoctrine()->getRepository(UserTraining::class)->find((int)$id);

        if($user_training && $user_training->getUser()->getId() === $this->getUser()->getId()){

            $form = $this->getSubscribeForm($user_training);
            $options = ['attr' => ['readonly' => true]];
            $form->add('notification_type', TextType::class,$options);


            return $this->render('user_training/view.html.twig', [
                'form' => $form->createView(),
                'user' => $this->getUser(),
                'training'=>$user_training->getGroupTraining(),
                'user_training'=>$user_training
            ]);


        }
        throw new NotFoundHttpException("Page not found");


    }

    public function edit($id, Request $request){
        try {
            new ReflectionClass('ReflectionClass' . ((int)$id . "" !== $id));
        } catch (Exception $e) {
            throw new NotFoundHttpException("Wrong input data");
        }

        $user_training = $this->getDoctrine()->getRepository(UserTraining::class)->find((int)$id);

        var_dump($user_training->getId());

        if($this->getUser()->getUserTrainings()->contains($user_training)){
            $notification_types_repository    = $this->getDoctrine()->getRepository(NotificationType::class);
            $training = $user_training->getGroupTraining();
            $form = $this->getSubscribeForm($user_training);
            $form->add('edit', SubmitType::class, ['label' => 'Edit', 'attr'=>['class' => 'btn btn-info btn-md', 'style' => 'float:right']]);

            $form->handleRequest($request);
            if ($request->isMethod('POST')) {
                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($user_training);
                    $entityManager->flush();

                    return $this->redirectToRoute('profile');
                }
            }

            return $this->render('user_training/subscribe.html.twig', [
                'form' => $form->createView(),
                'user' => $this->getUser(),
                'training'=>$training
            ]);


        }
        throw new NotFoundHttpException("Something went wrong");
    }

    public function remove($id = null){
        try {
            new ReflectionClass('ReflectionClass' . ((int)$id . "" !== $id));
        } catch (Exception $e) {
            throw new NotFoundHttpException("Wrong input data");
        }
        $repository = $this->getDoctrine()->getRepository(UserTraining::class);
        $userTraining = $repository->find((int)$id);

        $entityManager = $this->getDoctrine()->getManager();
        $userTraining->setIsDeleted(true);
        $entityManager->persist($userTraining);
        $entityManager->flush();
        return $this->redirectToRoute('profile');

    }

    private function getSubscribeForm($user_training){
        $form = $this->createFormBuilder($user_training)
            ->add('notification_type')
            ->getForm();
        return $form;
    }
}

fitnessclub/templates/user_training/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserTrainingController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/desig/PhpstormProjects/fitnessclub/src/Controller/UserTrainingController.php'|file_link(0) }}">src/Controller/UserTrainingController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/desig/PhpstormProjects/fitnessclub/templates/user_training/index.html.twig'|file_link(0) }}">templates/user_training/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

fitnessclub/templates/user_training/subscribe.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Data{% endblock %}

{% block body %}
    <div class="site-wrap">
        <div class="site-section">
            <div class="container text-center" style="width: 100%; height: 300px">
                <div class="col-md-4 text-center mb-4" style="width: 100%; height: 300px !important; max-width: 100% !important;">
                    <div class="border p-4" style="height: 300px; display: flex; justify-content: space-between">
                        <div id="subscribeData" style="float: left; text-align: left" class="col-md-4">
                            <div id="user">
                                <label class="label">
                                    User
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ user.firstname }} {{ user.lastname }}
                                </div>
                            </div>
                            <div id="training">
                                <label class="label">
                                    Training
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ training.name }}
                                </div>
                            </div>
                            <div id="master">
                                <label class="label">
                                    Master
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ training.masterName }}
                                </div>
                            </div>
                        </div>
                        <div id="form" style="width: 300px" class="col-md-5">
                            {{ form_start(form, {attr: {class: 'form',id: "login-form",novalidate: 'novalidate'}}) }}
                            <label class="form-check-label" for="not_type">
                                Notification Type
                            </label>
                            {{ form_widget(form.notification_type, { 'attr': {'class': 'custom-select custom-select-lg mb-3 text-uppercase','id':'not_type', 'required':'required'} }) }}
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

fitnessclub/templates/user_training/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Data{% endblock %}

{% block body %}
    <div class="site-wrap">

        <div class="site-section">
            <div class="row mb-5">
                <div class="col-md-12">
                    <h2 class="site-section-heading text-center">{{ training.name }}</h2>
                </div>
            </div>
            <div class="container text-center" style="width: 100%; height: 300px">
                <div class="col-md-4 text-center mb-4" style="width: 100%; height: 300px !important; max-width: 100% !important;">
                    <div class="border p-4" style="height: 400px; display: flex; justify-content: space-between">
                        <div id="subscribeData" style="float: left; text-align: left" class="col-md-8">
                            <div id="user">
                                <label class="label">
                                    User
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ user.firstname }} {{ user.lastname }}
                                </div>
                            </div>
                            <div id="training">
                                <label class="label">
                                    Training
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ training.name }}
                                </div>
                            </div>
                            <div id="master">
                                <label class="label">
                                    Master
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ training.masterName }}
                                </div>
                            </div>
                            <div id="description">
                                <label class="label">
                                    Description
                                </label>
                                <div id="userData" style="text-transform: uppercase; color: black">
                                    {{ training.description }}
                                </div>
                            </div>
                        </div>
                        <div id="form" style="width: 300px" class="col-md-4">
                            {{ form_start(form, {attr: {class: 'form',id: "login-form",novalidate: 'novalidate'}}) }}
                            <label class="form-check-label" for="not_type">
                                Notification Type
                            </label>
                            {{ form_widget(form.notification_type, { 'attr': {'class': 'custom-select custom-select-lg mb-3 text-uppercase','id':'not_type', 'required':'required'} }) }}
                            <p>
                                <a href="{{ path('editUserGroupTraining',{'id':user_training.id}) }}">Edit</a>
                            </p>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}