fitnessclub/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotNull(message="Firstname is required")
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $firstname;

    /**
     * @Assert\NotBlank(message="Lastname is required")
     * @ORM\Column(type="string", length=60)
     */
    private $lastname;

    /**
     * @Assert\Email(message="Wrong email")
     * @Assert\NotBlank(message="Email is required")
     * @ORM\Column(type="string", length=60, unique=true)
     */
    private $email;

    /**
     *
     * @Assert\Regex(pattern= "/[a-zA-Z0-9]/", message="Wrong characters")
     * @Assert\Length(
     *      min = 8,
     *      max = 100,
     *      minMessage = "Password short, min {{ limit }}",
     *      maxMessage = "Password long, max {{ limit }}"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @Assert\DateTime
     * @Assert\NotNull(message="Birthday is required")
     * @ORM\Column(type="datetime")
     */
    private $birthday;

    /**
     * @Assert\Regex(pattern= "/^[+]?\d+$/", message="Incorrect phone number")
     * @Assert\NotBlank(message="Phone is required")
     * @Assert\Length(
     *      min = 4,
     *      max = 20,
     *      minMessage = "Too short, min {{ limit }}",
     *      maxMessage = "Too long, max {{ limit }}"
     * )
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="json")
     */
    private $roles;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $auth_token;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_authorised;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_deleted;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserTraining", mappedBy="user")
     */
    private $userTrainings;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $is_active;

    /**
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @param mixed $image
     */
    public function setImage($image): void
    {
        $this->image = $image;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    public function __construct()
    {
        $this->userTrainings = new ArrayCollection();
    }

    /**
     * @param mixed $is_deleted
     */
    public function setIsDeleted(bool $is_deleted): self
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getisDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param mixed $is_authorised
     */
    public function setIsAuthorised(bool $is_authorised): self
    {
        $this->is_authorised = $is_authorised;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getIsAuthorised(): ?bool
    {
        return $this->is_authorised;
    }

    /**
     * @return mixed
     */
    public function getAuthToken()
    {
        return $this->auth_token;
    }

    /**
     * @param mixed $auth_token
     */
    public function setAuthToken($auth_token): void
    {
        $this->auth_token = $auth_token;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname($firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname($lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday($birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getRoles(): array
    {
        return array_unique($this->roles);
    }

    /**
     * @param mixed $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function unserialize($serialized)
    {
        list($this->id,
            $this->firstname,
            $this->lastname,
            $this->email,
            $this->password,
            $this->phone,
            $this->gender,
            $this->birthday,
            $this->roles,
            $this->is_authorised,
            $this->is_deleted
            ) = unserialize($serialized,['allowed_classes' => false]);
    }
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->firstname,
            $this->lastname,
            $this->email,
            $this->password,
            $this->phone,
            $this->gender,
            $this->birthday,
            $this->roles,
            $this->is_authorised,
            $this->is_deleted
        ]);
    }

    /**
     * @return Collection|UserTraining[]
     */
    public function getUserTrainings(): Collection
    {
        $array = new ArrayCollection();

        foreach ($this->userTrainings as $training){
            if(!$training->getIsDeleted()){
                $array->add($training);
            }
        }
        return $array;
    }

    public function addUserTraining(UserTraining $userTraining): self
    {
        if (!$this->userTrainings->contains($userTraining)) {
            $this->userTrainings[] = $userTraining;
            $userTraining->setUser($this);
        }

        return $this;
    }

    public function removeUserTraining(UserTraining $userTraining): self
    {
        if ($this->userTrainings->contains($userTraining)) {
            $this->userTrainings->removeElement($userTraining);
            // set the owning side to null (unless already changed)
            if ($userTraining->getUser() === $this) {
                $userTraining->setIsDeleted(true);
            }
        }

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->getFirstname().' '.$this->getLastname();
        // to show the id of the Category in the select
        // return $this->id;
    }

}

fitnessclub/templates/user/addUser.html.twig
{% extends 'adminBase.html.twig' %}
{% block title %}Admin{% endblock %}

{% block body %}
    {{ include('user/userEditForm.html.twig', { 'form': form}) }}
{% endblock %}

fitnessclub/templates/user/adminUserEdit.html.twig
{% extends 'adminBase.html.twig' %}
{% block title %}Admin{% endblock %}

{% block body %}
    {{ include('user/userEditForm.html.twig', { 'form': form}) }}
{% endblock %}

fitnessclub/templates/user/index.html.twig
{% extends 'adminBase.html.twig' %}
{% block title %}Admin{% endblock %}

{% block body %}
    {% for message in app.flashes('notice') %}
        <div class="alert alert-info collapse show" id="collapseNotice" data-toggle="collapse" data-target="#collapseNotice" aria-expanded="false">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.session.flashBag.get('userDeleted') %}
        <div class="alert alert-info collapse show" id="collapseDeleted" data-toggle="collapse" data-target="#collapseDeleted" aria-expanded="false">
            {{ message }}
        </div>
    {% endfor %}
    {% if users %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Firstname</th>
            <th scope="col">Lastname</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Gender</th>
            <th scope="col">Birtday</th>
            <th scope="col">Roles</th>
            <th scope="col">Is Authorised</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <th scope="row">{{ user.id }}</th>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.email }}</td>
                <th>{{ user.phone }}</th>
                <td>{{ user.gender }}</td>
                <td>{{ user.birthday|date("Y/m/d") }}</td>
                <td>{% for role in user.roles %}
                        {% if not loop.last %}
                            {{ role }}/
                        {% else %}
                            {{ role }}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ user.isAuthorised ? 'Yes':'No' }}</td>
                <td><a href="{{ path('editUser',{'id':user.id}) }}">Edit</a></td>
                <td><a href="{{ path('removeUser',{'id':user.id}) }}" onclick="return confirm('You want to delete {{ user.firstname }}?')">Remove</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <div class="alert alert-info" role="alert" style="text-align: center">
            You do not have any users
        </div>
    {% endif %}
{% endblock %}

fitnessclub/templates/user/userEditForm.html.twig
<div class="container">
    <div id="login-row" class="row justify-content-center align-items-center">
        <div id="login-column" class="col-md-6">
            <div id="login-box" class="col-md-12">

                {% for flash_message in app.session.flashBag.get('notice') %}
                    <div class="alert alert-success">
                        {{ flash_message }}
                    </div>
                {% endfor %}
                {{ form_start(form, {attr: {class: 'form',id: "login-form",novalidate: 'novalidate'}}) }}
                {% if form.firstname is defined %}
                    <div class="form-group">
                        {% if form_errors(form.firstname) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.firstname) }}
                            </div>
                        {% endif %}
                        <label for="firstname" class="text-info">Firstname</label><br>
                        {{ form_widget(form.firstname, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                {% endif %}
                {% if form.lastname is defined %}
                    <div class="form-group">
                        {% if form_errors(form.lastname) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.lastname) }}
                            </div>
                        {% endif %}
                        <label for="lastname" class="text-info">Lastname</label><br>
                        {{ form_widget(form.lastname, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                {% endif %}
                {% if form.email is defined %}
                    <div class="form-group">
                        {% if form_errors(form.email) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.email) }}
                            </div>
                        {% endif %}
                        <label for="email" class="text-info">Email</label><br>
                        {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                {% endif %}
                {% if form.gender is defined %}
                    <div class="form-group">
                        <label for="gender" class="text-info">Gender</label><br>
                        {{ form_widget(form.gender, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                {% endif %}
                {% if form.birthday is defined %}
                    <div class="form-group">
                        {% if form_errors(form.birthday) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.birthday) }}
                            </div>
                        {% endif %}
                        <label for="birthday" class="text-info">Birthday</label><br>
                        <div class="input-group date">
                            {{ form_widget(form.birthday, { 'attr': {'class': 'form-control', 'required':'required', 'onkeydown': "return false"} }) }}
                            <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                        </div>
                    </div>
                {% endif %}
                {% if form.phone is defined %}
                    <div class="form-group">
                        {% if form_errors(form.phone) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.phone) }}
                            </div>
                        {% endif %}
                        <label for="phone" class="text-info">Phone</label><br>
                        {{ form_widget(form.phone, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                {% endif %}
                {% if form.is_active is defined %}
                    <div class="form-group">
                        {% if form_errors(form.is_active) %}
                            <div class="alert alert-danger" role="alert" style="height: 50px">
                                {{ form_errors(form.is_active) }}
                            </div>
                        {% endif %}
                        <label class="form-check-label" for="isAuthorised">
                            Active
                        </label>
                        {{ form_widget(form.is_active, { 'attr': {'class': 'form-input', 'required':'required'} }) }}
                    </div>
                {% endif %}
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>